"""Esquema inicial limpio

Revision ID: e1ea56002978
Revises: 
Create Date: 2026-07-31 09:49:42.591482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.crypto import EncryptedString


# revision identifiers, used by Alembic.
revision: str = 'e1ea56002978'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banco_pago_movil', sa.String(length=100), nullable=True),
    sa.Column('telefono_pago_movil', sa.String(length=20), nullable=True),
    sa.Column('cedula_pago_movil', sa.String(length=20), nullable=True),
    sa.Column('banco_transferencia', sa.String(length=100), nullable=True),
    sa.Column('cuenta_transferencia', sa.String(length=50), nullable=True),
    sa.Column('correo_zelle', sa.String(length=200), nullable=True),
    sa.Column('correo_binance', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_pago_id'), 'configuracion_pago', ['id'], unique=False)
    op.create_table('logs_conciliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('monto_banco', sa.Float(), nullable=True),
    sa.Column('monto_reportado', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('respuesta_banco', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_conciliacion_id'), 'logs_conciliacion', ['id'], unique=False)
    op.create_table('niveles_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('monto_max_usd', sa.Float(), nullable=False),
    sa.Column('entrada_pct', sa.Float(), nullable=False),
    sa.Column('financia_pct', sa.Float(), nullable=False),
    sa.Column('cuotas_base', sa.Integer(), nullable=False),
    sa.Column('cuotas_max', sa.Integer(), nullable=False),
    sa.Column('mora_diaria', sa.Float(), nullable=False),
    sa.Column('aprobacion_extra', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel')
    )
    op.create_index(op.f('ix_niveles_config_id'), 'niveles_config', ['id'], unique=False)
    op.create_table('tasa_dolar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasa', sa.Float(), nullable=False),
    sa.Column('fuente', sa.String(length=100), nullable=True),
    sa.Column('actualizado_por', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasa_dolar_id'), 'tasa_dolar', ['id'], unique=False)
    op.create_table('tiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiendas_codigo'), 'tiendas', ['codigo'], unique=True)
    op.create_index(op.f('ix_tiendas_id'), 'tiendas', ['id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cedula', EncryptedString(length=500), nullable=False),
    sa.Column('cedula_hash', sa.String(length=64), nullable=True),
    sa.Column('telefono', EncryptedString(length=500), nullable=True),
    sa.Column('email', EncryptedString(length=500), nullable=True),
    sa.Column('direccion', EncryptedString(length=500), nullable=True),
    sa.Column('referencia_nombre', sa.String(length=200), nullable=True),
    sa.Column('referencia_telefono', sa.String(length=20), nullable=True),
    sa.Column('referencia_parentesco', sa.String(length=100), nullable=True),
    sa.Column('url_cedula', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('total_compras', sa.Integer(), nullable=True),
    sa.Column('total_monto_comprado_usd', sa.Float(), nullable=True),
    sa.Column('cuotas_pagadas_tiempo', sa.Integer(), nullable=True),
    sa.Column('cuotas_con_mora', sa.Integer(), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('token_app', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_clientes_cedula_hash'), 'clientes', ['cedula_hash'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_tienda_id'), 'clientes', ['tienda_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_tienda_id'), 'usuarios', ['tienda_id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=100), nullable=True),
    sa.Column('usuario_rol', sa.String(length=50), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('datos_antes', sa.JSON(), nullable=True),
    sa.Column('datos_despues', sa.JSON(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('metodo_http', sa.String(length=10), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_actual', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auditoria_accion', 'auditoria', ['accion'], unique=False)
    op.create_index('idx_auditoria_fecha', 'auditoria', ['fecha'], unique=False)
    op.create_index('idx_auditoria_tabla_registro', 'auditoria', ['tabla', 'registro_id'], unique=False)
    op.create_index('idx_auditoria_usuario', 'auditoria', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.create_table('financiamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_factura', sa.String(length=500), nullable=True),
    sa.Column('numero_factura', sa.String(length=100), nullable=True),
    sa.Column('monto_total_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_entrada_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_financia_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_cuota_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_total_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_entrada_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_financia_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_cuota_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tasa_aplicada', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('nivel_aplicado', sa.String(length=50), nullable=True),
    sa.Column('cuotas_solicitadas', sa.Integer(), nullable=False),
    sa.Column('cuotas_aprobadas', sa.Integer(), nullable=False),
    sa.Column('requiere_aprobacion', sa.Boolean(), nullable=True),
    sa.Column('aprobado_por', sa.String(length=50), nullable=True),
    sa.Column('entrada_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('financia_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_primera_cuota', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_financiamientos_cliente_id'), 'financiamientos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_financiamientos_id'), 'financiamientos', ['id'], unique=False)
    op.create_index(op.f('ix_financiamientos_tienda_id'), 'financiamientos', ['tienda_id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('cambiado_por', sa.String(length=200), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    op.create_table('cuotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financiamiento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('monto_base_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_base_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_interes_mora_bs', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monto_interes_mora_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monto_total_bs', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_total_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['financiamiento_id'], ['financiamientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuotas_financiamiento_id'), 'cuotas', ['financiamiento_id'], unique=False)
    op.create_index(op.f('ix_cuotas_id'), 'cuotas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financiamiento_id', sa.Integer(), nullable=False),
    sa.Column('cuota_id', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('monto_reportado_bs', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monto_confirmado_bs', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monto_original_bs', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('banco_origen', sa.String(length=100), nullable=True),
    sa.Column('telefono_pago', sa.String(length=20), nullable=True),
    sa.Column('cedula_pago', sa.String(length=20), nullable=True),
    sa.Column('comprobante', sa.String(length=500), nullable=True),
    sa.Column('modo_pago', sa.String(length=50), nullable=True),
    sa.Column('cuotas_incluidas', sa.Text(), nullable=True),
    sa.Column('pago_padre_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_rechazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conciliado_por', sa.String(length=100), nullable=True),
    sa.Column('rechazado_por', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuotas.id'], ),
    sa.ForeignKeyConstraint(['financiamiento_id'], ['financiamientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_cuota_id'), 'pagos', ['cuota_id'], unique=False)
    op.create_index(op.f('ix_pagos_financiamiento_id'), 'pagos', ['financiamiento_id'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_financiamiento_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_cuota_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_cuotas_id'), table_name='cuotas')
    op.drop_index(op.f('ix_cuotas_financiamiento_id'), table_name='cuotas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_financiamientos_tienda_id'), table_name='financiamientos')
    op.drop_index(op.f('ix_financiamientos_id'), table_name='financiamientos')
    op.drop_index(op.f('ix_financiamientos_cliente_id'), table_name='financiamientos')
    op.drop_table('financiamientos')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria')
    op.drop_index('idx_auditoria_tabla_registro', table_name='auditoria')
    op.drop_index('idx_auditoria_fecha', table_name='auditoria')
    op.drop_index('idx_auditoria_accion', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_tienda_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_tienda_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cedula_hash'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_tiendas_id'), table_name='tiendas')
    op.drop_index(op.f('ix_tiendas_codigo'), table_name='tiendas')
    op.drop_table('tiendas')
    op.drop_index(op.f('ix_tasa_dolar_id'), table_name='tasa_dolar')
    op.drop_table('tasa_dolar')
    op.drop_index(op.f('ix_niveles_config_id'), table_name='niveles_config')
    op.drop_table('niveles_config')
    op.drop_index(op.f('ix_logs_conciliacion_id'), table_name='logs_conciliacion')
    op.drop_table('logs_conciliacion')
    op.drop_index(op.f('ix_configuracion_pago_id'), table_name='configuracion_pago')
    op.drop_table('configuracion_pago')
    # ### end Alembic commands ###